//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hookah.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hookah.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account settings and more.
        /// </summary>
        public static string AccountSettingAndMore {
            get {
                return ResourceManager.GetString("AccountSettingAndMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new cathering event.
        /// </summary>
        public static string AddCatheringEvent {
            get {
                return ResourceManager.GetString("AddCatheringEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new FAQ question.
        /// </summary>
        public static string AddFaqQuestion {
            get {
                return ResourceManager.GetString("AddFaqQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new gallery item.
        /// </summary>
        public static string AddFooterGalaryItem {
            get {
                return ResourceManager.GetString("AddFooterGalaryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new fruit head.
        /// </summary>
        public static string AddFruitHead {
            get {
                return ResourceManager.GetString("AddFruitHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new link.
        /// </summary>
        public static string AddHomeLink {
            get {
                return ResourceManager.GetString("AddHomeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new step.
        /// </summary>
        public static string AddHowItWorksStep {
            get {
                return ResourceManager.GetString("AddHowItWorksStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addtions and Preferences.
        /// </summary>
        public static string Additions {
            get {
                return ResourceManager.GetString("Additions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new menu flavor.
        /// </summary>
        public static string AddMenuFlavor {
            get {
                return ResourceManager.GetString("AddMenuFlavor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new package.
        /// </summary>
        public static string AddPackage {
            get {
                return ResourceManager.GetString("AddPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users.
        /// </summary>
        public static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base title.
        /// </summary>
        public static string BaseTitle {
            get {
                return ResourceManager.GetString("BaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base title bold paragraph.
        /// </summary>
        public static string BaseTitleBoldText {
            get {
                return ResourceManager.GetString("BaseTitleBoldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base title paragraph.
        /// </summary>
        public static string BaseTitleText {
            get {
                return ResourceManager.GetString("BaseTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button text.
        /// </summary>
        public static string ButtonText {
            get {
                return ResourceManager.GetString("ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call button text.
        /// </summary>
        public static string CallButtonText {
            get {
                return ResourceManager.GetString("CallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassowrd {
            get {
                return ResourceManager.GetString("ConfirmPassowrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit cathering event.
        /// </summary>
        public static string EditCatheringEvent {
            get {
                return ResourceManager.GetString("EditCatheringEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current FAQ question.
        /// </summary>
        public static string EditFaqQuestion {
            get {
                return ResourceManager.GetString("EditFaqQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current gallery item.
        /// </summary>
        public static string EditFooterGalaryItem {
            get {
                return ResourceManager.GetString("EditFooterGalaryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit fruit head.
        /// </summary>
        public static string EditFruitHead {
            get {
                return ResourceManager.GetString("EditFruitHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit home link.
        /// </summary>
        public static string EditHomeLink {
            get {
                return ResourceManager.GetString("EditHomeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current step.
        /// </summary>
        public static string EditHowItWorksStep {
            get {
                return ResourceManager.GetString("EditHowItWorksStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string EditLower {
            get {
                return ResourceManager.GetString("EditLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit menu flavor.
        /// </summary>
        public static string EditMenuFlavor {
            get {
                return ResourceManager.GetString("EditMenuFlavor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit package.
        /// </summary>
        public static string EditPackage {
            get {
                return ResourceManager.GetString("EditPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event date.
        /// </summary>
        public static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra price per hour.
        /// </summary>
        public static string ExtraHourPrice {
            get {
                return ResourceManager.GetString("ExtraHourPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook profile link.
        /// </summary>
        public static string FacebookLink {
            get {
                return ResourceManager.GetString("FacebookLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flavors section text.
        /// </summary>
        public static string FlavorsText {
            get {
                return ResourceManager.GetString("FlavorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flavors section title.
        /// </summary>
        public static string FlavorsTitle {
            get {
                return ResourceManager.GetString("FlavorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form section title.
        /// </summary>
        public static string FormTile {
            get {
                return ResourceManager.GetString("FormTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruit heads section text.
        /// </summary>
        public static string FruitHeadText {
            get {
                return ResourceManager.GetString("FruitHeadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruit heads section title.
        /// </summary>
        public static string FruitHeadTitle {
            get {
                return ResourceManager.GetString("FruitHeadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many hourse of service.
        /// </summary>
        public static string HourseOfService {
            get {
                return ResourceManager.GetString("HourseOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works title.
        /// </summary>
        public static string HowItWorksTitle {
            get {
                return ResourceManager.GetString("HowItWorksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously added laptop size image.
        /// </summary>
        public static string ImageLP {
            get {
                return ResourceManager.GetString("ImageLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously added mobile size image.
        /// </summary>
        public static string ImageMB {
            get {
                return ResourceManager.GetString("ImageMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously added IPad size image.
        /// </summary>
        public static string ImagePL {
            get {
                return ResourceManager.GetString("ImagePL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial price.
        /// </summary>
        public static string InitialPrice {
            get {
                return ResourceManager.GetString("InitialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram profile link.
        /// </summary>
        public static string InstagramLink {
            get {
                return ResourceManager.GetString("InstagramLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram profile name.
        /// </summary>
        public static string InstagramProfileName {
            get {
                return ResourceManager.GetString("InstagramProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new item.
        /// </summary>
        public static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step order number.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order sended succesfully.
        /// </summary>
        public static string OrderSendedSuccessfully {
            get {
                return ResourceManager.GetString("OrderSendedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been accepted and you will be contacted soon.
        /// </summary>
        public static string OrderSendedSuccessfullyText {
            get {
                return ResourceManager.GetString("OrderSendedSuccessfullyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order title.
        /// </summary>
        public static string OrderTitle {
            get {
                return ResourceManager.GetString("OrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string PackageItem {
            get {
                return ResourceManager.GetString("PackageItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string Packages {
            get {
                return ResourceManager.GetString("Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph text.
        /// </summary>
        public static string PageParagraphText {
            get {
                return ResourceManager.GetString("PageParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number for calling.
        /// </summary>
        public static string PhoneNumberForCall {
            get {
                return ResourceManager.GetString("PhoneNumberForCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously uploaded image.
        /// </summary>
        public static string PreviousUploadedImage {
            get {
                return ResourceManager.GetString("PreviousUploadedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request call button text.
        /// </summary>
        public static string RequestCallButton {
            get {
                return ResourceManager.GetString("RequestCallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request sended succesfully.
        /// </summary>
        public static string RequestSendedSuccessfully {
            get {
                return ResourceManager.GetString("RequestSendedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been accepted and you will be contacted soon.
        /// </summary>
        public static string RequestSendedSuccessfullyText {
            get {
                return ResourceManager.GetString("RequestSendedSuccessfullyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select package title.
        /// </summary>
        public static string SelectPackageTitle {
            get {
                return ResourceManager.GetString("SelectPackageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string StepText {
            get {
                return ResourceManager.GetString("StepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin.
        /// </summary>
        public static string SuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of package.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top image title.
        /// </summary>
        public static string TopImageTitle {
            get {
                return ResourceManager.GetString("TopImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter profile link.
        /// </summary>
        public static string TwitterLink {
            get {
                return ResourceManager.GetString("TwitterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okey.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube profile link.
        /// </summary>
        public static string YoutubeLink {
            get {
                return ResourceManager.GetString("YoutubeLink", resourceCulture);
            }
        }
    }
}
